export let resourceNewData: Object[] = [
  {
    TaskID: 1,
    TaskName: 'Rohan G',
    StartDate: new Date('04/02/2022'),
    EndDate: new Date('04/21/2022'),
    Skills: 'html, css, java',
    ProjectManeger: 'Jeevan',

    // subtasks: [
    //     { TaskID: 2, TaskName: 'Defining the product and its usage', StartDate: new Date('04/02/2022'), Duration: 3, Progress: 30 },
    //     { TaskID: 3, TaskName: 'Defining target audience', StartDate: new Date('04/02/2022'), Duration: 3 },
    //     {
    //         TaskID: 4, TaskName: 'Prepare product sketch and notes', StartDate: new Date('04/02/2022'), Duration: 2,
    //         Predecessor: '2', Progress: 30
    //     },
    // ]
  },
  {
    TaskID: 2,
    TaskName: 'John',
    StartDate: new Date('04/02/2022'),
    EndDate: new Date('04/21/2022'),
    Skills: 'html, css, java',
    ProjectManeger: 'Sumit',
  },
  {
    TaskID: 3,
    TaskName: 'Alex Portman',
    StartDate: new Date('04/02/2022'),
    EndDate: new Date('04/21/2022'),
    Skills: 'html, css, java',
    ProjectManeger: 'Sumit',
  },
  // subtasks: [
  //   {
  //     TaskID: 7,
  //     TaskName: 'Demand analysis',
  //     StartDate: new Date('04/04/2022'),
  //     EndDate: new Date('04/21/2022'),
  //     subtasks: [
  //       {
  //         TaskID: 8,
  //         TaskName: 'Customer strength',
  //         StartDate: new Date('04/04/2022'),
  //         Duration: 4,
  //         Predecessor: '5',
  //         Progress: 30,
  //       },
  //       {
  //         TaskID: 9,
  //         TaskName: 'Market opportunity analysis',
  //         StartDate: new Date('04/04/2022'),
  //         Duration: 4,
  //         Predecessor: '5',
  //       },
  //     ],
  //   },
  //   {
  //     TaskID: 10,
  //     TaskName: 'Competitor analysis',
  //     StartDate: new Date('04/04/2022'),
  //     Duration: 4,
  //     Predecessor: '7, 8',
  //     Progress: 30,
  //   },
  //   {
  //     TaskID: 11,
  //     TaskName: 'Product strength analsysis',
  //     StartDate: new Date('04/04/2022'),
  //     Duration: 4,
  //     Predecessor: '9',
  //   },
  //   {
  //     TaskID: 12,
  //     TaskName: 'Research complete',
  //     StartDate: new Date('04/04/2022'),
  //     Duration: 0,
  //     Predecessor: '10',
  //     Indicators: [
  //       {
  //         date: '04/20/2022',
  //         name: 'Research completed',
  //         tooltip: 'Research completed',
  //         iconClass: 'description e-icons',
  //       },
  //     ],
  //   },
  // ],
  {
    TaskID: 4,
    TaskName: 'Scarlet Jules',
    StartDate: new Date('04/04/2022'),
    EndDate: new Date('04/21/2022'),
    Skills: 'html, css, python',
    ProjectManeger: 'Sumit',

    // subtasks: [
    //   {
    //     TaskID: 14,
    //     TaskName: 'Functionality design',
    //     StartDate: new Date('04/04/2022'),
    //     Duration: 3,
    //     Progress: 30,
    //     Predecessor: '12',
    //   },
    //   {
    //     TaskID: 15,
    //     TaskName: 'Quality design',
    //     StartDate: new Date('04/04/2022'),
    //     Duration: 3,
    //     Predecessor: '12',
    //   },
    //   {
    //     TaskID: 16,
    //     TaskName: 'Define reliability',
    //     StartDate: new Date('04/04/2022'),
    //     Duration: 2,
    //     Progress: 30,
    //     Predecessor: '15',
    //   },
    //   {
    //     TaskID: 17,
    //     TaskName: 'Identifying raw materials',
    //     StartDate: new Date('04/04/2022'),
    //     Duration: 2,
    //     Predecessor: '15',
    //   },
    //   {
    //     TaskID: 18,
    //     TaskName: 'Define cost plan',
    //     StartDate: new Date('04/04/2022'),
    //     EndDate: new Date('04/21/2022'),
    //     subtasks: [
    //       {
    //         TaskID: 19,
    //         TaskName: 'Manufacturing cost',
    //         StartDate: new Date('04/04/2022'),
    //         Duration: 2,
    //         Progress: 30,
    //         Predecessor: '17',
    //       },
    //       {
    //         TaskID: 20,
    //         TaskName: 'Selling cost',
    //         StartDate: new Date('04/04/2022'),
    //         Duration: 2,
    //         Predecessor: '17',
    //       },
    //     ],
    //   },
    //   {
    //     TaskID: 21,
    //     TaskName: 'Development of the final design',
    //     StartDate: new Date('04/04/2022'),
    //     EndDate: new Date('04/21/2022'),
    //     subtasks: [
    //       {
    //         TaskID: 22,
    //         TaskName: 'Defining dimensions and package volume',
    //         StartDate: new Date('04/04/2022'),
    //         Duration: 2,
    //         Progress: 30,
    //         Predecessor: '19,20',
    //       },
    //       {
    //         TaskID: 23,
    //         TaskName: 'Develop design to meet industry standards',
    //         StartDate: new Date('04/04/2022'),
    //         Duration: 2,
    //         Predecessor: '22',
    //       },
    //       {
    //         TaskID: 24,
    //         TaskName: 'Include all the details',
    //         StartDate: new Date('04/04/2022'),
    //         Duration: 3,
    //         Predecessor: '23',
    //       },
    //     ],
    //   },
    //   {
    //     TaskID: 25,
    //     TaskName: 'CAD computer-aided design',
    //     StartDate: new Date('04/04/2022'),
    //     Duration: 3,
    //     Progress: 30,
    //     Predecessor: '24',
    //   },
    //   {
    //     TaskID: 26,
    //     TaskName: 'CAM computer-aided manufacturing',
    //     StartDate: new Date('04/04/2022'),
    //     Duration: 3,
    //     Predecessor: '25',
    //   },
    //   {
    //     TaskID: 27,
    //     TaskName: 'Design complete',
    //     StartDate: new Date('04/04/2022'),
    //     Duration: 0,
    //     Predecessor: '26',
    //   },
    // ],
  },
  {
    TaskID: 5,
    TaskName: 'Robert',
    StartDate: new Date('04/04/2022'),
    Duration: 4,
    Progress: 30,
    Predecessor: '27',
    Skills: 'spark, java, python',
    ProjectManeger: 'Sumit',
  },
  {
    TaskID: 6,
    TaskName: 'Michael',
    StartDate: new Date('04/04/2022'),
    Duration: 4,
    Skills: 'html, css, java',
    ProjectManeger: 'Jeevan',
    // Predecessor: '28ss',
    // Indicators: [
    //   {
    //     date: '05/24/2022',
    //     name: 'Production phase',
    //     tooltip: 'Production phase completed',
    //     iconClass: 'okIcon e-icons',
    //   },
    // ],
  },
  {
    TaskID: 7,
    TaskName: 'Thomas',
    StartDate: new Date('04/04/2022'),
    Duration: 5,
    Progress: 30,
    Predecessor: '28,29',
    Skills: 'html, css, java',
    ProjectManeger: 'Jeevan',
  },
  {
    TaskID: 8,
    TaskName: 'Joseph',
    StartDate: new Date('04/04/2022'),
    Duration: 5,
    Predecessor: '30',
    Skills: 'html, css, python',
    ProjectManeger: 'Sumit',
  },
  {
    TaskID: 9,
    TaskName: 'Charles',
    StartDate: new Date('04/04/2022'),
    EndDate: new Date('04/21/2022'),
    Skills: 'html, css, java',
    ProjectManeger: 'Sumit',
    // subtasks: [
    //   {
    //     TaskID: 33,
    //     TaskName: 'Internal testing and feedback',
    //     StartDate: new Date('04/04/2022'),
    //     Duration: 3,
    //     Progress: 45,
    //     Predecessor: '31',
    //   },
    //   {
    //     TaskID: 34,
    //     TaskName: 'Customer testing and feedback',
    //     StartDate: new Date('04/04/2022'),
    //     Duration: 3,
    //     Progress: 50,
    //     Predecessor: '33',
    //   },
    // ],
  },
  {
    TaskID: 10,
    TaskName: 'Daniel',
    StartDate: new Date('04/04/2022'),
    EndDate: new Date('04/21/2022'),
    Skills: 'html, css, java',
    ProjectManeger: 'Sumit',
    // subtasks: [
    //   {
    //     TaskID: 36,
    //     TaskName: 'Important improvements',
    //     StartDate: new Date('04/04/2022'),
    //     Duration: 4,
    //     Progress: 30,
    //     Predecessor: '34',
    //   },
    //   {
    //     TaskID: 37,
    //     TaskName: 'Address any unforeseen issues',
    //     StartDate: new Date('04/04/2022'),
    //     Duration: 4,
    //     Progress: 30,
    //     Predecessor: '36ss',
    //     Indicators: [
    //       {
    //         date: '06/21/2022',
    //         name: 'Sales and marketing',
    //         tooltip: 'Sales and marketing',
    //         iconClass: 'description e-icons',
    //       },
    //     ],
    //   },
    // ],
  },
  {
    TaskID: 11,
    TaskName: 'Mathew',
    StartDate: new Date('04/04/2022'),
    EndDate: new Date('04/21/2022'),
    Skills: 'html, css, java',
    ProjectManeger: 'Sumit',
    // subtasks: [
    //   {
    //     TaskID: 39,
    //     TaskName: 'Branding product',
    //     StartDate: new Date('04/04/2022'),
    //     Duration: 4,
    //     Predecessor: '37',
    //   },
    //   {
    //     TaskID: 40,
    //     TaskName: 'Marketing and presales',
    //     StartDate: new Date('04/04/2022'),
    //     Duration: 4,
    //     Progress: 30,
    //     Predecessor: '39',
    //   },
    // ],
  },
];
export let projectNewData: Object[] = [
  {
    TaskID: 1,
    TaskName: 'Resource Utilization Site',
    StartDate: new Date('04/02/2022'),
    EndDate: new Date('04/21/2022'),
    subtasks: [
      {
        TaskID: 'a',
        TaskName: 'Building the architecture',
        StartDate: new Date('04/02/2022'),
        Duration: 3,
        Progress: 30,
      },
      {
        TaskID: 'b',
        TaskName: 'Merging the Files and making the master files',
        StartDate: new Date('04/02/2022'),
        Duration: 3,
      },
      {
        TaskID: 'c',
        TaskName: 'Importing excel sheet in angualr',
        StartDate: new Date('04/02/2022'),
        Duration: 2,
        Predecessor: '2',
        Progress: 30,
      },
      {
        TaskID: 'd',
        TaskName: 'Working on Dashboard',
        StartDate: new Date('04/02/2022'),
        Duration: 2,
        Predecessor: '2',
        Progress: 30,
      },
    ],
  },
  {
    TaskID: 2,
    TaskName: 'Women Saftey Dashboard',
    StartDate: new Date('04/02/2022'),
    Duration: 0,
    Predecessor: '3,4',
    Indicators: [
      {
        date: '04/10/2022',
        name: 'Design Phase',
        tooltip: 'Design phase completed',
        iconClass: 'okIcon e-icons',
      },
    ],
  },
  {
    TaskID: 3,
    TaskName: 'Millennial Garage Website',
    StartDate: new Date('04/02/2022'),
    EndDate: new Date('04/21/2022'),
    subtasks: [
      {
        TaskID: 4,
        TaskName: 'Demand analysis',
        StartDate: new Date('04/04/2022'),
        EndDate: new Date('04/21/2022'),
        subtasks: [
          {
            TaskID: 'a',
            TaskName: 'Customer strength',
            StartDate: new Date('04/04/2022'),
            Duration: 4,
            Predecessor: '5',
            Progress: 30,
          },
          {
            TaskID: 'b',
            TaskName: 'Market opportunity analysis',
            StartDate: new Date('04/04/2022'),
            Duration: 4,
            Predecessor: '5',
          },
        ],
      },
      {
        TaskID: 'c',
        TaskName: 'Competitor analysis',
        StartDate: new Date('04/04/2022'),
        Duration: 4,
        Predeces4or: '7, 8',
        Progress: 30,
      },
      {
        TaskID: 'd',
        TaskName: 'Product strength analsysis',
        StartDate: new Date('04/04/2022'),
        Duration: 4,
        Predecessor: '9',
      },
      {
        TaskID: 'e',
        TaskName: 'Research complete',
        StartDate: new Date('04/04/2022'),
        Duration: 0,
        Predecessor: '10',
        Indicators: [
          {
            date: '04/20/2022',
            name: 'Research completed',
            tooltip: 'Research completed',
            iconClass: 'description e-icons',
          },
        ],
      },
    ],
  },
  {
    TaskID: 5,
    TaskName: 'EDA Dashboard',
    StartDate: new Date('04/04/2022'),
    EndDate: new Date('04/21/2022'),
    subtasks: [
      {
        TaskID: 'a',
        TaskName: 'Functionality design',
        StartDate: new Date('04/04/2022'),
        Duration: 3,
        Progress: 30,
        Predecessor: '12',
      },
      {
        TaskID: 'b',
        TaskName: 'Quality design',
        StartDate: new Date('04/04/2022'),
        Duration: 3,
        Predecessor: '12',
      },
      {
        TaskID: 'c',
        TaskName: 'Define reliability',
        StartDate: new Date('04/04/2022'),
        Duration: 2,
        Progress: 30,
        Predecessor: '15',
      },
      {
        TaskID: 'd',
        TaskName: 'Identifying raw materials',
        StartDate: new Date('04/04/2022'),
        Duration: 2,
        Predecessor: '15',
      },
      {
        TaskID: 6,
        TaskName: 'Define cost plan',
        StartDate: new Date('04/04/2022'),
        EndDate: new Date('04/21/2022'),
        subtasks: [
          {
            TaskID: 'a',
            TaskName: 'Manufacturing cost',
            StartDate: new Date('04/04/2022'),
            Duration: 2,
            Progress: 30,
            Predecessor: '17',
          },
          {
            TaskID: 'b',
            TaskName: 'Selling cost',
            StartDate: new Date('04/04/2022'),
            Duration: 2,
            Predecessor: '17',
          },
        ],
      },
      {
        TaskID: 7,
        TaskName: 'Development of the final design',
        StartDate: new Date('04/04/2022'),
        EndDate: new Date('04/21/2022'),
        subtasks: [
          {
            TaskID: 'a',
            TaskName: 'Defining dimensions and package volume',
            StartDate: new Date('04/04/2022'),
            Duration: 2,
            Progress: 30,
            Predecessor: '19,20',
          },
          {
            TaskID: 'b',
            TaskName: 'Develop design to meet industry standards',
            StartDate: new Date('04/04/2022'),
            Duration: 2,
            Predecessor: '22',
          },
          {
            TaskID: 'c',
            TaskName: 'Include all the details',
            StartDate: new Date('04/04/2022'),
            Duration: 3,
            Predecessor: '23',
          },
        ],
      },
      {
        TaskID: 'd',
        TaskName: 'CAD computer-aided design',
        StartDate: new Date('04/04/2022'),
        Duration: 3,
        Progress: 30,
        Predecessor: '24',
      },
      {
        TaskID: 'e',
        TaskName: 'CAM computer-aided manufacturing',
        StartDate: new Date('04/04/2022'),
        Duration: 3,
        Predecessor: '25',
      },
      {
        TaskID: '*',
        TaskName: 'Design complete',
        StartDate: new Date('04/04/2022'),
        Duration: 0,
        Predecessor: '26',
      },
    ],
  },
  {
    TaskID: 'A',
    TaskName: 'Prototype testing',
    StartDate: new Date('04/04/2022'),
    Duration: 4,
    Progress: 30,
    Predecessor: '27',
  },
  {
    TaskID: 'B',
    TaskName: 'Include feedback',
    StartDate: new Date('04/04/2022'),
    Duration: 4,
    Predecessor: '28ss',
    Indicators: [
      {
        date: '05/24/2022',
        name: 'Production phase',
        tooltip: 'Production phase completed',
        iconClass: 'okIcon e-icons',
      },
    ],
  },
  {
    TaskID: 'C',
    TaskName: 'Manufacturing',
    StartDate: new Date('04/04/2022'),
    Duration: 5,
    Progress: 30,
    Predecessor: '28,29',
  },
  {
    TaskID: 'D',
    TaskName: 'Assembling materials to finsihed goods',
    StartDate: new Date('04/04/2022'),
    Duration: 5,
    Predecessor: '30',
  },
  {
    TaskID: 8,
    TaskName: 'Feedback and testing',
    StartDate: new Date('04/04/2022'),
    EndDate: new Date('04/21/2022'),
    subtasks: [
      {
        TaskID: 'a',
        TaskName: 'Internal testing and feedback',
        StartDate: new Date('04/04/2022'),
        Duration: 3,
        Progress: 45,
        Predecessor: '31',
      },
      {
        TaskID: 'b',
        TaskName: 'Customer testing and feedback',
        StartDate: new Date('04/04/2022'),
        Duration: 3,
        Progress: 50,
        Predecessor: '33',
      },
    ],
  },
  {
    TaskID: 9,
    TaskName: 'Final product development',
    StartDate: new Date('04/04/2022'),
    EndDate: new Date('04/21/2022'),
    subtasks: [
      {
        TaskID: 'a',
        TaskName: 'Important improvements',
        StartDate: new Date('04/04/2022'),
        Duration: 4,
        Progress: 30,
        Predecessor: '34',
      },
      {
        TaskID: 'b',
        TaskName: 'Address any unforeseen issues',
        StartDate: new Date('04/04/2022'),
        Duration: 4,
        Progress: 30,
        Predecessor: '36ss',
        Indicators: [
          {
            date: '06/21/2022',
            name: 'Sales and marketing',
            tooltip: 'Sales and marketing',
            iconClass: 'description e-icons',
          },
        ],
      },
    ],
  },
  {
    TaskID: 10,
    TaskName: 'Final product',
    StartDate: new Date('04/04/2022'),
    EndDate: new Date('04/21/2022'),
    subtasks: [
      {
        TaskID: 'a',
        TaskName: 'Branding product',
        StartDate: new Date('04/04/2022'),
        Duration: 4,
        Predecessor: '37',
      },
      {
        TaskID: 'b',
        TaskName: 'Marketing and presales',
        StartDate: new Date('04/04/2022'),
        Duration: 4,
        Progress: 30,
        Predecessor: '39',
      },
    ],
  },
];
